--Utilization_vw
CREATE VIEW Utilization_vw AS SELECT -- ORDER Information
OH.ORDER_ID,
OH.STATUS AS ORDER_STATUS,
OH.SOURCE,
OH.ACCOUNT_ID,
OH.PLANT_ID,
OH.CURRENCY,
OH.TRANSPORT_MODE,
OH.DELIVERY_DATE,
-- ORDER Line Information
OL.LINE_NUMBER,
OL.ITEM_ID,
OL.ITEM_NAME,
OL.SKU_ID,
OL.UOM,
OL.QUANTITY,
OL.BASE_UNITS,
-- Utilization Metrics Header
UM.ID AS UTILIZATION_ID,
UM.VARIANT_ID,
UM.NUMBER_OF_CONTAINERS,
UM.MAX_UTILIZATION_PCT,
UM.MAX_LAST_CONTAINER_PCT,
-- Utilization ROWS
UR.ROW_TYPE,
UR.METRIC AS UTILIZATION_METRIC,
UR.CAPACITY,
UR.ACTUAL,
UR.GAP,
UR.UTILIZATION_PCT,
-- Equipment
EQ.NAME AS EQUIPMENT_NAME,
EQ.WEIGHT_IN_TONS,
EQ.PALLET_COUNT AS EQUIPMENT_PALLET_COUNT,
-- Container
C.CONTAINER_ID,
C.LABEL AS CONTAINER_LABEL,
C.CONTAINER_TYPE,
C.LENGTH AS CONTAINER_LENGTH,
C.WIDTH AS CONTAINER_WIDTH,
C.HEIGHT AS CONTAINER_HEIGHT,
C.PALLET_COUNT AS CONTAINER_PALLET_COUNT,
C.MAX_UTILIZATION_PCT AS CONTAINER_MAX_UTILIZATION,
-- Container Metrics
CM.METRIC AS CONTAINER_METRIC,
CM.CAPACITY AS CONTAINER_CAPACITY,
CM.ACTUAL AS CONTAINER_ACTUAL,
CM.GAP AS CONTAINER_GAP,
CM.UTILIZATION_PCT AS CONTAINER_UTILIZATION_PCT,
-- Pallet
P.ID AS PALLET_ID,
P.PALLET_NAME,
P.GROUP_NAME,
P.PALLET_TYPE,
P.CATEGORY,
P.PALLET_HEIGHT_OCCUPIED,
P.PALLET_VOLUME_OCCUPIED,
P.PALLET_WEIGHT_OCCUPIED,
P.WEIGHT_CAPACITY,
P.VOLUME_CAPACITY,
-- Pallet Details
PD.KIT,
PD.SKU,
PD.CUSTOMER_GROUP,
PD.MATERIAL_GROUP,
PD.QUANTITY AS PALLET_QTY,
PD.WEIGHT_PER_UNIT,
PD.VOLUME_PER_UNIT,
PD.TOTAL_WEIGHT,
PD.TOTAL_VOLUME,
PD.DANGEROUS_GOODS,
PD.DESCRIPTION
FROM
    Order_Header OH
    LEFT JOIN Order_LineItem OL ON OH.ORDER_ID = OL.ORDER_ID
    LEFT JOIN Utilization_Metrics UM ON OH.ORDER_ID = UM.ORDER_ID
    LEFT JOIN Utilization_Rows UR ON UM.ID = UR.METRICS_ID
    LEFT JOIN Equipment EQ ON OH.ORDER_ID = EQ.ORDER_ID
    LEFT JOIN Container C ON OH.ORDER_ID = C.ORDER_ID
    LEFT JOIN Container_Metrics CM ON C.CONTAINER_ID = CM.CONTAINER_ID
    LEFT JOIN Pallet P ON C.CONTAINER_ID = P.CONTAINER_ID
    LEFT JOIN Pallet_Details PD ON P
.ID
=
    PD.PALLET_ID;

GO

