/*
Utilization:
Order_Header
Order_LineItem
Utilization_Metrics
Utilization_Rows
Equipment
Container
Container_Metrics
Pallet
Pallet_Details


Optimization:
Order_Header
Order_LineItem
KIT_HEADER
KIT_DETAILS
VARIANT_SUMMARY
VARIANT_METRICS
*/

-- Microsoft Fabric Warehouse DDL

CREATE TABLE Order_Header (
    ORDER_ID VARCHAR(1000),
    STATUS VARCHAR(100),
    SOURCE VARCHAR(100),
    ACCOUNT_ID VARCHAR(100),
    PLANT_ID VARCHAR(1000),
    CURRENCY VARCHAR(1000),
    SOLD_TO VARCHAR(1000),
    SHIP_TO VARCHAR(1000),
    TRANSPORT_MODE VARCHAR(1000),
    DELIVERY_DATE DATETIME2(6),
    SALES_DOCUMENT_DATE DATETIME2(6),
    AL_SYNC_TIMESTAMP FLOAT,
    CREATED_AT DATETIME2(6),
    UPDATED_AT DATETIME2(6),
    STATUS_DE VARCHAR(1000)
);

CREATE TABLE Order_LineItem (
    ID VARCHAR(1000),
    ORDER_ID VARCHAR(1000),
    LINE_NUMBER VARCHAR(1000),
    ITEM_TYPE VARCHAR(100),
    ITEM_ID VARCHAR(100),
    ITEM_NAME VARCHAR(500),
    SKU_ID VARCHAR(1000),
    UOM VARCHAR(1000),
    BASE_UNITS VARCHAR(1000),
    QUANTITY FLOAT,
    ROW_HASH FLOAT,
    ORDER_CLOSED VARCHAR(1000),
    AL_SYNC_TIMESTAMP FLOAT,
    CREATED_AT DATETIME2(6),
    UPDATED_AT DATETIME2(6),
    ConfdDeliveryQtyInBaseUnit FLOAT
);

CREATE TABLE Container (
    ID VARCHAR(1000),
    ORDER_ID VARCHAR(1000),
    VARIANT_ID FLOAT,
    CONTAINER_ID VARCHAR(100),
    LABEL VARCHAR(255),
    CONTAINER_TYPE VARCHAR(100),
    LENGTH FLOAT,
    WIDTH FLOAT,
    HEIGHT FLOAT,
    PALLET_COUNT FLOAT,
    MAX_UTILIZATION_PCT VARCHAR(1000),
    CREATED_AT DATETIME2(6),
    UPDATED_AT DATETIME2(6)
);

CREATE TABLE Container_Metrics (
    ID VARCHAR(1000),
    CONTAINER_ID VARCHAR(1000),
    METRIC VARCHAR(100),
    CAPACITY FLOAT,
    ACTUAL FLOAT,
    GAP FLOAT,
    UTILIZATION_PCT FLOAT,
    CREATED_AT DATETIME2(6),
    UPDATED_AT DATETIME2(6)
);

CREATE TABLE Optimized_variant (
    ID VARCHAR(1000),
    VARIANT_ID VARCHAR(100),
    ORDER_ID VARCHAR(1000),
    TITLE VARCHAR(1255),
    UPDATED_AT DATETIME2(6)
);

CREATE TABLE Pallet (
    ID VARCHAR(1000),
    CONTAINER_ID VARCHAR(1000),
    PALLET_NAME VARCHAR(255),
    GROUP_NAME VARCHAR(255),
    LENGTH FLOAT,
    WIDTH FLOAT,
    HEIGHT FLOAT,
    MAX_HEIGHT FLOAT,
    MIXING VARCHAR(1000),
    PALLET_FILL VARCHAR(1000),
    WEIGHT_CAPACITY FLOAT,
    VOLUME_CAPACITY FLOAT,
    ADDRESS_X VARCHAR(1000),
    ADDRESS_Y VARCHAR(1000),
    ADDRESS_Z VARCHAR(1000),
    PALLET_HEIGHT_OCCUPIED FLOAT,
    CATEGORY VARCHAR(100),
    PALLET_TYPE VARCHAR(100),
    PALLET_VOLUME_OCCUPIED FLOAT,
    PALLET_WEIGHT_OCCUPIED FLOAT,
    TEMPERATURE VARCHAR(100),
    CREATED_AT DATETIME2(6),
    UPDATED_AT DATETIME2(6)
);

CREATE TABLE Pallet_Details (
    ID VARCHAR(1000),
    PALLET_ID VARCHAR(1000),
    KIT VARCHAR(1000),
    SKU VARCHAR(1000),
    CUSTOMER_GROUP VARCHAR(255),
    TEMPERATURE VARCHAR(100),
    MATERIAL_GROUP VARCHAR(255),
    QUANTITY VARCHAR(1000),
    WEIGHT_PER_UNIT FLOAT,
    VOLUME_PER_UNIT FLOAT,
    TOTAL_WEIGHT VARCHAR(1000),
    TOTAL_VOLUME FLOAT,
    REMARKS VARCHAR(1000),
    PB_MATERIAL_GROUP FLOAT,
    DANGEROUS_GOODS VARCHAR(100),
    DANGEROUS_FLAG VARCHAR(1000),
    DESCRIPTION VARCHAR(1000),
    PACKAGE_SIZE VARCHAR(255),
    TYPE VARCHAR(100),
    CREATED_AT DATETIME2(6),
    UPDATED_AT DATETIME2(6)
);

CREATE TABLE Parts (
    ID VARCHAR(1000),
    KIT_DETAIL_ID VARCHAR(1000),
    PART VARCHAR(1000),
    SIZE VARCHAR(1000),
    PART_QTY FLOAT,
    CREATED_AT DATETIME2(6),
    UPDATED_AT DATETIME2(6)
);

CREATE TABLE Utilization_Metrics (
    ID VARCHAR(1000),
    ORDER_ID VARCHAR(1000),
    VARIANT_ID FLOAT,
    NUMBER_OF_CONTAINERS FLOAT,
    MAX_UTILIZATION_PCT FLOAT,
    MAX_LAST_CONTAINER_PCT FLOAT,
    CREATED_AT DATETIME2(6),
    UPDATED_AT DATETIME2(6)
);

CREATE TABLE Utilization_Rows (
    ID VARCHAR(1000),
    METRICS_ID VARCHAR(1000),
    ROW_TYPE VARCHAR(100),
    METRIC VARCHAR(100),
    CAPACITY FLOAT,
    ACTUAL FLOAT,
    GAP FLOAT,
    UTILIZATION_PCT FLOAT,
    CREATED_AT DATETIME2(6),
    UPDATED_AT DATETIME2(6)
);

CREATE TABLE Container_Table (
    ID VARCHAR(1000),
    CONTAINER_ID VARCHAR(1000),
    KIT VARCHAR(1000),
    PART_QUANTITY FLOAT,
    PALLET_COUNT FLOAT,
    WEIGHT FLOAT,
    CREATED_AT DATETIME2(6),
    UPDATED_AT DATETIME2(6)
);

CREATE TABLE Equipment (
    ID VARCHAR(1000),
    ORDER_ID VARCHAR(1000),
    NAME VARCHAR(255),
    WEIGHT_IN_TONS FLOAT,
    PALLET_COUNT FLOAT,
    CREATED_AT DATETIME2(6),
    UPDATED_AT DATETIME2(6)
);

CREATE TABLE KIT_DETAILS (
    ID VARCHAR(1000),
    KIT_HEADER_ID VARCHAR(1000),
    KIT VARCHAR(1000),
    KIT_QTY VARCHAR(1000),
    BASE_UNITS VARCHAR(1000),
    TOTAL_UOM VARCHAR(1000),
    CREATED_AT DATETIME2(6),
    UPDATED_AT DATETIME2(6)
);

CREATE TABLE KIT_HEADER (
    ID VARCHAR(1000),
    ORDER_ID VARCHAR(1000),
    PLANT VARCHAR(1000),
    COUNTRY VARCHAR(100),
    SHIP_TO VARCHAR(1000),
    SOLD_TO VARCHAR(1000),
    CUSTOMER_GROUP VARCHAR(255),
    TRANSPORT_MODE VARCHAR(1000),
    SHIPPING_CONDITIONS VARCHAR(1000),
    CREATED_AT DATETIME2(6),
    UPDATED_AT DATETIME2(6)
);

CREATE TABLE VARIANT_SUMMARY (
    ID VARCHAR(1000),
    ORDER_ID VARCHAR(1000),
    VARIANT_ID VARCHAR(100),
    ITEM_ID VARCHAR(100),
    ITEM_NAME VARCHAR(500),
    SKU_ID VARCHAR(1000),
    BASE_UNITS VARCHAR(1000),
    ORIGINAL_QTY FLOAT,
    PROPOSED_QTY FLOAT,
    CHANGE_QTY FLOAT,
    FORECAST_QTY FLOAT,
    DELIVERED_QTY FLOAT,
    CREATED_AT DATETIME2(6),
    UPDATED_AT DATETIME2(6)
);

CREATE TABLE VARIANT_METRICS (
    ID VARCHAR(1000),
    ORDER_ID VARCHAR(1000),
    VARIANT_ID VARCHAR(100),
    TYPE VARCHAR(100),
    NUMBER_OF_CONTAINERS FLOAT,
    MAX_UTILIZATION_PCT FLOAT,
    MAX_UTILIZATION_LAST_TRUCK FLOAT,
    LAST_TRUCK_WEIGHT FLOAT,
    LAST_TRUCK_UTILIZATION FLOAT,
    LAST_TRUCK_PALLETS FLOAT,
    LAST_PALLET_UTILIZATION FLOAT,
    CREATED_AT DATETIME2(6),
    UPDATED_AT DATETIME2(6)
);
