CREATE TABLE [dbo].[KIT_DETAILS] (
    [ID]            VARCHAR (1000) NULL,
    [KIT_HEADER_ID] VARCHAR (1000) NULL,
    [KIT]           VARCHAR (1000) NULL,
    [KIT_QTY]       VARCHAR (1000) NULL,
    [BASE_UNITS]    VARCHAR (1000) NULL,
    [TOTAL_UOM]     VARCHAR (1000) NULL,
    [CREATED_AT]    DATETIME2 (6)  NULL,
    [UPDATED_AT]    DATETIME2 (6)  NULL
);


GO

