CREATE TABLE [dbo].[VARIANT_SUMMARY] (
    [ID]            VARCHAR (1000) NULL,
    [ORDER_ID]      VARCHAR (1000) NULL,
    [VARIANT_ID]    VARCHAR (100)  NULL,
    [ITEM_ID]       VARCHAR (100)  NULL,
    [ITEM_NAME]     VARCHAR (500)  NULL,
    [SKU_ID]        VARCHAR (1000) NULL,
    [BASE_UNITS]    VARCHAR (1000) NULL,
    [ORIGINAL_QTY]  FLOAT (53)     NULL,
    [PROPOSED_QTY]  FLOAT (53)     NULL,
    [CHANGE_QTY]    FLOAT (53)     NULL,
    [FORECAST_QTY]  FLOAT (53)     NULL,
    [DELIVERED_QTY] FLOAT (53)     NULL,
    [CREATED_AT]    DATETIME2 (6)  NULL,
    [UPDATED_AT]    DATETIME2 (6)  NULL
);


GO

